# Exception is an error in your program
try:
    print(x)

except:
    print("An error occurred")

finally:
    print("Success")
